version: '3.6'

services:

  backend:
    container_name: backend
    build: ./backend
    networks:
    - external
    ports:
    - 3000:3000
    restart: always
    depends_on:
      - recommendation-api

  frontend:
    container_name: frontend
    build: ./frontend
    networks:
    - external
    ports:
    - 8080:8080
    restart: always
    depends_on:
      - backend
      - recommendation-api

  recommendation-api:
    container_name: recommendation-api
    build: ./recommendation-api
    networks:
    - external
    ports:
    - 5000:5000
    restart: always
    volumes:
      - model_volume:/models
  
networks:
  external:
    driver: bridge

volumes:
  model_volume:
    name: "model_volume"
    driver_opts:
      type: none
      o: bind
      device: /home/dima/dev/findmyseries/recommendation-api/models
