apiVersion: v1
kind: Service
metadata:
  name: recommendation-api
  namespace: findmyseries
  labels:
    app: recommendation-api
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  selector:
    app: recommendation-api

